// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvbSNLJx1gvBZHUKh6SwXEexMXFrcfK8',
    appId: '1:1067693404188:web:05a8bab709b543aff56fd9',
    messagingSenderId: '1067693404188',
    projectId: 'fitnessgym-e7d87',
    authDomain: 'fitnessgym-e7d87.firebaseapp.com',
    storageBucket: 'fitnessgym-e7d87.firebasestorage.app',
    measurementId: 'G-BJLWTBD3N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJ3cv8TI_e7vBsNb_kOZdB-TYgHnkuTM',
    appId: '1:1067693404188:android:0e48b40d72392dc5f56fd9',
    messagingSenderId: '1067693404188',
    projectId: 'fitnessgym-e7d87',
    storageBucket: 'fitnessgym-e7d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Wdj2Wnyi3scm1oh5agmMsbp4MTRR0xA',
    appId: '1:1067693404188:ios:e94110e534dfe449f56fd9',
    messagingSenderId: '1067693404188',
    projectId: 'fitnessgym-e7d87',
    storageBucket: 'fitnessgym-e7d87.firebasestorage.app',
    iosBundleId: 'com.example.gymManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Wdj2Wnyi3scm1oh5agmMsbp4MTRR0xA',
    appId: '1:1067693404188:ios:e94110e534dfe449f56fd9',
    messagingSenderId: '1067693404188',
    projectId: 'fitnessgym-e7d87',
    storageBucket: 'fitnessgym-e7d87.firebasestorage.app',
    iosBundleId: 'com.example.gymManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANvbSNLJx1gvBZHUKh6SwXEexMXFrcfK8',
    appId: '1:1067693404188:web:c91ad11f6c43ea25f56fd9',
    messagingSenderId: '1067693404188',
    projectId: 'fitnessgym-e7d87',
    authDomain: 'fitnessgym-e7d87.firebaseapp.com',
    storageBucket: 'fitnessgym-e7d87.firebasestorage.app',
    measurementId: 'G-1KQM1Z4EVC',
  );
}
